name: remote_cam_client
description: Remote camera control client application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  path_provider: ^2.1.1
  path: ^1.8.3
  permission_handler: ^11.0.1
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  flutter_mjpeg: ^2.0.4
  open_file: ^3.3.2
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
