name: helloknightrcc_server
description: Remote camera server application
publish_to: 'none'
version: 1.0.6+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  path: ^1.8.3
  image: ^4.1.3
  sqflite: ^2.3.0
  package_info_plus: ^8.0.0
  dio: ^5.4.0
  url_launcher: ^6.2.5
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/VERSION

